# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: required
apt_packages:
- unixodbc-dev

r_github_packages:
 - hannesmuehleisen/MonetDBLite

script: 
    - |
    R CMD build .
    travis_wait 20 R CMD check convey*tar.gz